config/routes.rb
Rails.application.routes.draw do
  resources :text_blocks
  resources :blog_posts do
    
  end
  post 'blog_posts/:id/text_blocks/new', to: 'blog_posts#new_text_block', as: 'blog_posts_new_text_block'
  root to: 'blog_posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/text_block.rb
class TextBlock < ApplicationRecord
    belongs_to :blog_post
    acts_as_list scope: :blog_post
    has_many :internal_links, foreign_key: 'source_id', dependent: :destroy
    has_many :destinations, through: :internal_links, foreign_key: 'destination_id', class_name: 'BlogPost'
    before_save :handle_internal_links

    def handle_internal_links
        self.prune_links
        
    end

    def prune_links
        self.internal_links.each do |link|
            puts "making sure #{link.inspect} has a destination"
            unless(BlogPost.find_by(id: link.destination_id))
                puts self.internal_links.methods
                link.destroy

            end
        end
    end

    

    def display
        puts 'displaying'

    end
end

app/controllers/text_blocks_controller.rb
class TextBlocksController < ApplicationController
  before_action :set_text_block, only: [:show, :edit, :update, :destroy]

  # GET /text_blocks
  # GET /text_blocks.json
  def index
    @text_blocks = TextBlock.all
  end

  # GET /text_blocks/1
  # GET /text_blocks/1.json
  def show
  end

  # GET /text_blocks/new
  def new
    @text_block = TextBlock.new
  end

  # GET /text_blocks/1/edit
  def edit
    
  end

  # POST /text_blocks
  # POST /text_blocks.json
  def create
    @text_block = TextBlock.new(text_block_params)

    respond_to do |format|
      if @text_block.save
        format.html { redirect_to @text_block, notice: 'Text block was successfully created.' }
        format.json { render :show, status: :created, location: @text_block }
      else
        format.html { render :new }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_blocks/1
  # PATCH/PUT /text_blocks/1.json
  def update
    respond_to do |format|
      if @text_block.update(text_block_params)
        format.html { redirect_to @text_block, notice: 'Text block was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_block }
      else
        format.html { render :edit }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_blocks/1
  # DELETE /text_blocks/1.json
  def destroy
    @text_block.destroy
    respond_to do |format|
      format.html { redirect_to text_blocks_url, notice: 'Text block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_block
      @text_block = TextBlock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def text_block_params
      params.require(:text_block).permit(:body)
    end
end

app/helpers/text_blocks_helper.rb
module TextBlocksHelper
end

app/views/text_blocks/_creator.html.erb
<div id='text-block-creator'class='text-block'>
    <div class='text-block-text-area'>
        ...
    </div>
</div>

app/views/text_blocks/_form.html.erb
<%= form_with(model: text_block, local: true) do |form| %>
  <% if text_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text_block.errors.count, "error") %> prohibited this text_block from being saved:</h2>

      <ul>
        <% text_block.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/text_blocks/_text_block.html.erb
<div id='text-block-<%= text_block.id %>'class='text-block'>
    <div class='text-block-text-area'>
        <%= text_block.body %>
    </div>
</div>

app/views/text_blocks/edit.html.erb
<%= render 'form', text_block: @text_block %>

app/views/text_blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Text Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class='text-block-container' data-selected='none'>
    <% @text_blocks.each do |text_block| %>
      <tr>
        <td><%= render partial: 'text_blocks/text_block', locals: { text_block: text_block } %></td>
        <td><%= link_to 'Show', text_block %></td>
        <td><%= link_to 'Edit', edit_text_block_path(text_block) %></td>
        <td><%= link_to 'Destroy', text_block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text Block', new_text_block_path %>
<%= javascript_pack_tag 'edit_mode' %>

app/views/text_blocks/new.html.erb
<h1>New Text Block</h1>

<%= render 'form', text_block: @text_block %>

<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p class='text-block-container'>
  <strong>Body:</strong>
  <%= render @text_block %>
</p>

<%= link_to 'Edit', edit_text_block_path(@text_block) %> |
<%= link_to 'Back', text_blocks_path %>